base_url = "https://ahphoo.github.io/"
compile_sass = true
title = "Algostructures"
highlight_code = true
highlight_theme = "kronuz"
build_search_index = true

taxonomies = [
    {name = "tags", rss = true},
    {name = "authors", rss = true},
]
